default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: b_scraper_development

test:
  <<: *default
  database: b_scraper_test

production:
  <<: *default
  database: b_scraper_production
  username: b_scraper
  password: <%= ENV["B_SCRAPER_DATABASE_PASSWORD"] %>
